### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by emijrp** [imdario/pipar#1]
Hello, can you please run the script and update the data? I talked with you some weeks ago. Just a reminder

**Comment by darccio** [comment]
Voy a preparar un update.

**Comment by emijrp** [comment]
Ayer abrí el issue #2 por si pudieras arreglarlo antes de relanzarlo.

**Comment by darccio** [comment]
Pues después de pelearme estas últimas horas, no consigue que funcione. Bajo Mac OS X el Firefox arranca pero hace segfault. Bajo Linux me salen problemas varios ajenos a Pipar (SELinux restrictivo en un servidor, versiones de Ruby en otro, etc).

Intentaré echarle otro rato mañana.

**Comment by darccio** [comment]
Bueno, por fin he conseguido que esto funcione. No acabo de comprender el asunto pero he montado un contenedor Docker y ahí funcione perfectamente bajo Ruby 2.1 y últimas versiones de dependencias.

Publicaré la información actualizado cuando esté. Tarda bastante.

**Comment by emijrp** [comment]
Gracias!

**Comment by darccio** [comment]
Repositorio actualizado con la información actualizada a fecha de hoy. Cierro issue.
